<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1736818578987' stop='1736818588458'>
    <name>Testa envio de formulario</name>
    <title>Testa envio de formulario</title>
    <test-cases>
        <test-case start='1736818578997' status='failed' stop='1736818588457'>
            <name>Formulario enviado com sucesso</name>
            <title>Formulario enviado com sucesso</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>Timed out retrying after 4000ms: Expected to find content: 'Mensagem enviada para Igor!' but never did.</message>
                <stack-trace>AssertionError: Timed out retrying after 4000ms: Expected to find content: 'Mensagem enviada para Igor!' but never did.
                    at Context.eval (webpack://portfolio/./cypress/e2e/GUI/validarFormularioDeContato.cy.js:11:49)</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>